/*
 * Copyright 2014-2019 Netflix, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'com.netflix.nebula.plugin-plugin'
    id "org.jetbrains.kotlin.jvm" version "2.4.10"
    id 'java-gradle-plugin'
}

description 'Gradle plugin to allow locking of dynamic dependency versions'


group = 'com.netflix.nebula'

contacts {
    'nebula-plugins-oss@netflix.com' {
        moniker 'Nebula Plugins Maintainers'
        github 'nebula-plugins'
    }
}

dependencies {
    implementation 'com.squareup.moshi:moshi:1.12.+'
    implementation 'org.apache.commons:commons-lang3:3.12.0'
    implementation 'joda-time:joda-time:2.10'
    implementation('com.netflix.nebula:nebula-dependencies-comparison:latest.release') {
        exclude module: 'groovy-all'
    }

    implementation platform("com.fasterxml.jackson:jackson-bom:2.14.2")

    testImplementation 'com.netflix.nebula:nebula-test:latest.release'
    // nebula-test no longer exposes its Spock support as transitive API dependencies.
    testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'
    testImplementation 'org.spockframework:spock-junit4:2.3-groovy-4.0'
    testImplementation gradleTestKit()
    testImplementation "com.github.tomakehurst:wiremock:2.17.0"
    testImplementation 'com.github.stefanbirkner:system-rules:1.19.0'
    testImplementation 'org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r'
    testImplementation("org.assertj:assertj-core:3.27.7")
    testImplementation("org.eclipse.jgit:org.eclipse.jgit:7.+")
}

configurations.all {
    resolutionStrategy {
        force 'org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r'
    }
}
gradlePlugin {
    plugins {
        dependencyLock {
            id = 'com.netflix.nebula.dependency-lock'
            displayName = 'Nebula Dependency Lock plugin'
            implementationClass = 'nebula.plugin.dependencylock.DependencyLockPlugin'
            description = 'Plugin to lock dynamic dependencies'
            tags.set(['nebula', 'dependencies', 'lock'])

        }
    }
}

tasks.named('compileGroovy') {
    // Groovy only needs the declared dependencies
    // and not the output of compileJava
    classpath = sourceSets.main.compileClasspath
}
tasks.named('compileKotlin') {
    // Kotlin also depends on the result of Groovy compilation
    // which automatically makes it depend of compileGroovy
    libraries.from(files(sourceSets.main.groovy.classesDirectory))
}

test.dependsOn jar

tasks.withType(Test).configureEach {
    // Ensure test failures fail the build (overrides any plugin that sets ignoreFailures)
    ignoreFailures = false
    develocity.testRetry {
        maxRetries = 3
        maxFailures = 20
    }
}

testing {
    suites {
        it.named("test", JvmTestSuite) {
            it.useJUnitJupiter()
            it.targets {
                it.all {
                    it.testTask.configure {
                        maxParallelForks = 4
                        testLogging {
                            events "PASSED", "FAILED", "SKIPPED"
                        }
                    }
                }
            }
        }
    }
}

tasks.wrapper {
    distributionType = Wrapper.DistributionType.BIN
    gradleVersion = "9.2.1"
    distributionSha256Sum = "72f44c9f8ebcb1af43838f45ee5c4aa9c5444898b3468ab3f4af7b6076c5bc3f"
}